### PR TITLE
Upgrading to Babel 6

### PR DESCRIPTION
**Pull request by jburich**

### CODE REVIEW

**Comment by lucasbento** [comment]
@johanneslumpe: can you merge this? seems to be good.

**Comment by johanneslumpe** [comment]
@jburich thanks!

**Comment by axe-me** [comment]
@jburich seems need to increase the package version . still getting old code install thru npm/yarn

**Comment by jburich** [comment]
usually the version number is handled as part of the release process. @johanneslumpe I didn't bump the version number in my pull request. Would you like me to update this branch with a new version number or can you just run another release and bump the version number?

**Comment by johanneslumpe** [comment]
@ShaneXie @jburich I'll do it today!

**Comment by johanneslumpe** [comment]
published as `0.3.0`

**Pull request merged**
